package Glot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_fetch extends EnumerationDescriptorBase {

  public EnumerationDescriptor_fetch() {
    super(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x71f9e3fbbf8a7ddcL, "fetch", "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/8212846065876631004");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_fetch_0 = new EnumerationDescriptor.MemberDescriptor("fetch", "fetch", 0x71f9e3fbbf8a7dddL, "r:2949c8b3-848f-4943-96d9-40c6f576f822(Glot.structure)/8212846065876631005");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x28e4957b85994380L, 0x9a2de36d611c13b9L, 0x71f9e3fbbf8a7ddcL, 0x71f9e3fbbf8a7dddL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_fetch_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "fetch":
        return myMember_fetch_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
